name: CI-FRONT

on: 
  push:
    branches:
    - develop

defaults:
  run:
    working-directory: Wirtualnik.Frontend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.5
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2.1.6
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install project dependencies
      run: yarn --prefer-offline
    
    - name: Generate prod
      run: yarn build

    - name: Copy .nuxt
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: /home/runner/work/Wirtualnik/Wirtualnik/Wirtualnik.Frontend/.nuxt/
        remote: ${{ secrets.REMOTE_FRONT_TARGET }}/.nuxt
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Copy static
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: /home/runner/work/Wirtualnik/Wirtualnik/Wirtualnik.Frontend/static/
        remote: ${{ secrets.REMOTE_FRONT_TARGET }}/static
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Copy nuxt.config.js
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: /home/runner/work/Wirtualnik/Wirtualnik/Wirtualnik.Frontend/nuxt.config.js
        remote: ${{ secrets.REMOTE_FRONT_TARGET }}/nuxt.config.js
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Copy package.json
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: /home/runner/work/Wirtualnik/Wirtualnik/Wirtualnik.Frontend/package.json
        remote: ${{ secrets.REMOTE_FRONT_TARGET }}/package.json
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Copy yarn.lock
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: /home/runner/work/Wirtualnik/Wirtualnik/Wirtualnik.Frontend/yarn.lock
        remote: ${{ secrets.REMOTE_FRONT_TARGET }}/yarn.lock
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.6.4
      with:
        command: yarn --cwd ${{ secrets.REMOTE_FRONT_TARGET }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.6.4
      with:
        command: sudo pm2 reload npm
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
