name: CI-FRONT

on: 
  push:
    branches:
    - develop

defaults:
  run:
    working-directory: frontend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: yarn
    
    - name: Generate prod
      run: yarn build

    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: frontend/.nuxt
        remote: ${{ secrets.REMOTE_FRONT_TARGET }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    # - name: Run SSH command
    #   uses: garygrossgarten/github-action-ssh@v0.6.4
    #   with:
    #     command: sudo systemctl restart wirtualnik.service
    #     host: ${{ secrets.REMOTE_HOST }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     privateKey: ${{ secrets.REMOTE_SSH_KEY }}
