name: CI-FRONT

on: 
  push:
    branches:
    - develop

defaults:
  run:
    working-directory: Wirtualnik.Frontend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Get yarn cache directory path
       id: yarn-cache-dir-path
       run: echo "::set-output name=dir::$(yarn cache dir)"

     - uses: actions/cache@v1
       id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
       with:
         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
         restore-keys: |
           ${{ runner.os }}-yarn-

    - name: Install project dependencies
      run: yarn --prefer-offline
    
    - name: Generate prod
      run: yarn build

    - name: test
      run: pwd

    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: /home/runner/work/Wirtualnik/Wirtualnik/Wirtualnik.Frontend/.nuxt/
        remote: ${{ secrets.REMOTE_FRONT_TARGET }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}

    # - name: Run SSH command
    #   uses: garygrossgarten/github-action-ssh@v0.6.4
    #   with:
    #     command: sudo systemctl restart wirtualnik.service
    #     host: ${{ secrets.REMOTE_HOST }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     privateKey: ${{ secrets.REMOTE_SSH_KEY }}
