# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/Wirtualnik.Frontend"
    schedule:
      interval: "daily"

  # Maintain dependencies for NuGet
  - package-ecosystem: "nuget"
    directory: "/Wirtualnik.NET"
    schedule:
      interval: "daily"
