name: Check .NET project building

# Eventually this script should run after the PR is created and commit is sent.
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=14.10
    
    - name: Set default Xcode 12.3
      run: |
        XCODE_ROOT=/Applications/Xcode_12.3.0.app
        echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
        sudo xcode-select -s $XCODE_ROOT
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    # We need to use NuGet because Xamarin doesn't like dotnet restore
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
        
    - name: Run NuGet Restore
    - run: nuget restore Wirtualnik.NET/Wirtualnik.sln

    - name: Build Wirtualnik.Data
      run: dotnet build Wirtualnik.NET/Wirtualnik.Data/Wirtualnik.Data.csproj --configuration Release --no-restore
      
    - name: Build Wirtualnik.Repository
      run: dotnet build -restore Wirtualnik.NET/Wirtualnik.Repository/Wirtualnik.Repository.csproj --configuration Release --no-restore
      
    - name: Build Wirtualnik.Server
      run: dotnet build -restore Wirtualnik.NET/Wirtualnik.Server/Wirtualnik.Server.csproj --configuration Release --no-restore
      
    - name: Build Wirtualnik.Shared
      run: dotnet build -restore Wirtualnik.NET/Wirtualnik.Shared/Wirtualnik.Shared.csproj --configuration Release --no-restore
      
    - name: Build Wirtualnik.XF
      run: msbuild -restore Wirtualnik.NET/Wirtualnik.XF/Wirtualnik.XF.csproj
      
    - name: Wirtualnik.XF.Android
      run: msbuild -restore Wirtualnik.NET/Wirtualnik.XF.Android/Wirtualnik.XF.Android.csproj
      
      # We don't have macOS machine locally, so building iOS app is pointless.
    # - name: Build Wirtualnik.XF.iOS
    #  run: msbuild -restore Wirtualnik.NET/Wirtualnik.XF.iOS/Wirtualnik.XF.iOS.csproj
      
      # We don't have tests for now.
    # - name: Test run: dotnet test --no-build --verbosity normal
