name: Forntend project building

# Eventually this script should run after the PR is created and commit is sent.
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./Wirtualnik.Frontend
        run: yarn install
      
      - name: Build Wirtualnik.Frontend
        working-directory: ./Wirtualnik.Frontend
        run: yarn build
      
